name: PR Agent

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    name: Review pull requests
    steps:
      - name: PR Agent
        id: pragent
        uses: docker://pragent/pr-agent:0.44.0-github_action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_AI_STUDIO.GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          config.model: "gemini/gemini-3.7-flash"
          config.fallback_models: '["gemini/gemini-2.5-flash"]'
          config.verbosity_level: "2"
          github_action_config.auto_review: "true"
          github_action_config.auto_describe: "false"
          github_action_config.auto_improve: "false"
          github_action_config.pr_actions: '["opened", "reopened", "ready_for_review"]'
